seed: 111
train:
  setting: semi-supervised
  lr: 0.001
  epochs: 100
  eval_epochs: 10
  batch_size: 64
data:
  name: 6_cardio.npz
  path: ad_bench
  normalize: true
model:
  hidden_dim: [512, 512]
  activation: lrelu
diffusion:
  num_timesteps: 50
  beta_start: 0.0001
  beta_end: 0.02
  scheduler: linear
  time_emb_dim: 4
  time_emb_type: sinusoidal
